# This is a basic workflow to help you get started with Actions

name: Create Executable file

# Controls when the workflow will run
on:
  # Triggers the workflow on push request events but only for the "main" branch
  pull_request:
    types: [ "closed" ]
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: windows-latest
    if: github.event.pull_request.merged == true

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      